
- hosts:
    - all
  remote_user: ec2-user
  become: yes

  gather_facts: no

  pre_tasks:
    - name: Update cache
      raw: yum repolist

  roles:
    - initOS
    - amznCodeDeployAgent
    - amznSSMAgent
    - systemUtils
    - hardenSSHD
    - cleanupOS

